# This workflow watches for new commits on the develop branch of the repository https://github.com/niketagrawal/tudat, and if there is a new commit on the develop branch, it bumps the version in the current repository using the command bump2version patch --config-file .bumpversion.cfg --verbose and pushes the tag to the repository.

name: Watch tudat and bump version

on:
    workflow_dispatch:
    

jobs:
    watch_tudat_bump_version:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: develop

            - name: Check for new commits on tudat develop branch
              run: |
                  git clone --branch develop https://github.com/niketagrawal/tudat.git tudat-repo
                  cd tudat-repo
                  NEW_COMMITS=$(git log origin/develop --not --remotes=origin/develop)
                  if [ -z "$NEW_COMMITS" ]; then
                      echo "No new commits found."
                      exit 0
                  else
                      echo "New commits found."
                  fi

            - name: Install bump2version
              run: pip install bump2version

            - name: Bump version
              id: bump_version
              run: |
                  git config --global user.email "actions@github.com"
                  git config --global user.name "GitHub Actions"
                  bump2version dev --config-file .bumpversion.cfg --verbose
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Push tag to tudat-feedstock
              run: git push origin --follow-tags
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

