# This workflow checks every 10 minutes if there is a new commit on the develop branch of the GitHub repository https://github.com/tudat-team/tudat, and if there is a new commit on the develop branch, it bumps the version using the command bump2version patch --config-file .bumpversion.cfg --verbose and pushes the tag to the repository.

name: Watch tudat and bump version

on:
    workflow_dispatch:
    schedule:
        - cron: '*/10 * * * *'

jobs:
    bump_version:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: develop
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.10
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install bump2version
            - name: Bump version
              run: |
                  bump2version patch --config-file .bumpversion.cfg --verbose
            - name: Push tag
              run: |
                  git push origin --follow-tags


